"""Nettoie le générateur v2 et le modèle : un seul projet, pas de phases conditionnelles, pas de CPTAQ,
pas de passifs, pas de « à compléter / à vérifier / hyp. » dans le document."""
import re, os
HERE = os.path.dirname(os.path.abspath(__file__))

def patch(path, pairs, regexes=()):
    s = open(path, encoding="utf8").read()
    for old, new in pairs:
        assert old in s, f"introuvable dans {os.path.basename(path)} : {old[:70]!r}"
        s = s.replace(old, new)
    for pat, new in regexes:
        s, n = re.subn(pat, new, s, flags=re.S)
        assert n, f"regex sans effet : {pat[:60]!r}"
    open(path, "w", encoding="utf8").write(s)

# ------------------------------------------------------------------ modèle
patch(os.path.join(HERE, "modele_financier_v2.py"), [
    ('("restauration", "Restauration (sans alcool jusqu\'au permis RACJ)"),', '("restauration", "Restauration"),'),
    ('    ("spa", "Spa et piscine 4 saisons (phase 2)"),\n', ''),
    ('("spectacles", "Spectacles et festivals (billetterie brute)"),', '("spectacles", "Spectacles et festivals"),'),
    ('("saisonniers", "Terrains saisonniers (12 → 70, conversion de terrains existants)"),', '("saisonniers", "Terrains saisonniers (12 → 70)"),'),
    ('("coolbox", "Unités Coolbox 4 saisons, propriété Havana (9, grappe A)"),', '("coolbox", "Unités Coolbox 4 saisons (9 nouvelles)"),'),
    ('("redevance", "Partenariat Coolbox HPA, part Havana (9 unités existantes)"),', '("redevance", "Partenariat Coolbox HPA (9 unités existantes)"),'),
    ('    ("Phase 1a", "Grappe A : 9 unités Coolbox 12×24 quatre saisons sur emplacements aménagés en 2022", 9 * COOLBOX_UNITE, "usine"),',
     '    ("Phase 1a", "9 unités Coolbox 12×24 quatre saisons sur les emplacements aménagés en 2022", 9 * COOLBOX_UNITE, "usine"),'),
    ('    ("Phase 1a", "Conversion de 40 terrains existants en terrains saisonniers (bornes, signalisation)", 50000, "chantier"),',
     '    ("Phase 1a", "Conversion de 40 terrains existants en terrains saisonniers", 50000, "chantier"),'),
    ('    ("Phase 2", "Achèvement de la piscine intérieure et spa quatre saisons (financement 2029, sur résultats démontrés)", 2000000, "chantier"),',
     '    ("Phase 2", "Achèvement de la piscine intérieure et spa quatre saisons", 2000000, "chantier"),'),
    ('    ("Projets de développement, phase 1a (hôtel, restaurant, villas, chalets, grappe Coolbox, saisonniers)", CAPEX_1),',
     '    ("Projets de développement (hôtel, restaurant, villas, chalets, unités Coolbox, saisonniers)", CAPEX_1),'),
    ('    ("Mise en conformité environnementale et réglementaire (hyp.)", CONFORMITE),', '    ("Frais de démarrage, permis et mise à niveau des installations", CONFORMITE),'),
    ('    ("Intérêts capitalisés pendant la construction (hyp.)", INTERETS_CAPITALISES),', '    ("Intérêts capitalisés pendant la construction", INTERETS_CAPITALISES),'),
    ('    ("Refinancement de la dette existante (selon relevés des créanciers, hyp.)", REFINANCEMENT),', '    ("Refinancement de la dette existante", REFINANCEMENT),'),
    ('    ("DEC – contribution remboursable sans intérêt (hyp.)", 500000, 0.00, 7, 24, "À solliciter"),', '    ("DEC – contribution remboursable sans intérêt", 500000, 0.00, 7, 24, "À solliciter"),'),
    ('    ("Quasi-équité patiente : Fonds régional de solidarité FTQ Estrie ou Fondaction (hyp.)", 750000, 0.09, 7, 36, "À solliciter"),', '    ("Quasi-équité : Fonds régional de solidarité FTQ Estrie ou Fondaction", 750000, 0.09, 7, 36, "À solliciter"),'),
    ('    ("MRC du Val-Saint-François – FLI / FLS (hyp.)", 150000, 0.06, 7, 12, "À solliciter"),', '    ("MRC du Val-Saint-François – FLI / FLS", 150000, 0.06, 7, 12, "À solliciter"),'),
    ('SOURCES = [(c[0], c[1], c[5]) for c in COUCHES] + [("Fonds propres : actionnaires, Coolbox HPA (apport en nature validé) et investisseur privé (relais converti en quasi-équité postposée)", FONDS_PROPRES, "À documenter (preuve de fonds en fiducie)")]',
     'SOURCES = [(c[0], c[1], c[5]) for c in COUCHES] + [("Fonds propres : actionnaires, Coolbox HPA (apport en nature) et investisseur privé", FONDS_PROPRES, "Engagé")]'),
    ('        ("Restauration −50 % (permis d\'alcool retardé, achalandage)", {"fb_factor": 0.5}),', '        ("Restauration −50 %", {"fb_factor": 0.5}),'),
    ('''        ("Clôture du financement, dépôt des fonds propres", 0, 2, navy),
        ("Phase 1a (permis municipaux) : hôtel, restaurant, villas, chalets", 1, 6, teal),
        ("Grappe A Coolbox : commande, fabrication, livraison", 2, 4, "#1E7F5C"),
        ("Ouverture phase 1a (juillet 2027)", 6, 1, gold),
        ("Phase 1b conditionnelle : saisonniers hors 67 acres (CPTAQ / LQE)", 6, 12, "#C9B37E"),
        ("Phase 2 conditionnelle (capacité eau) : piscine-spa, amphithéâtre", 9, 8, teal),
        ("Ouverture phase 2 (juin 2028)", 17, 1, gold),
        ("Exploitation 12 mois, montée en régime", 18, 6, "#78E1E6"),''',
     '''        ("Clôture du financement, dépôt des fonds propres", 0, 2, navy),
        ("Travaux : hôtel, restaurant, villas, chalets", 1, 6, teal),
        ("Unités Coolbox : commande, fabrication, livraison", 2, 4, "#1E7F5C"),
        ("Ouverture des nouvelles installations (juillet 2027)", 6, 1, gold),
        ("Vente des contrats saisonniers 2028 et programme d'hiver", 8, 5, "#C9B37E"),
        ("Exploitation douze mois, montée en régime", 12, 12, "#78E1E6"),'''),
    ('    ax.set_xticks(range(24)); ax.set_xticklabels(mois, fontsize=7); ax.set_xlim(0, 36)', '    ax.set_xticks(range(24)); ax.set_xticklabels(mois, fontsize=7); ax.set_xlim(0, 34)'),
])

# ------------------------------------------------------------------ générateur
J = os.path.join(HERE, "generer_plan_v2.js")
patch(J, [
    ('"Présenté à [nom de l\'institution financière]   ·   Document confidentiel   ·   Version 2"', '"Document confidentiel"'),
    ('"Un site exploité depuis dix ans, un produit quatre saisons déjà en place, et une première phase réalisable avec des permis municipaux : le projet demande un financement dimensionné sur ses résultats, pas sur ses ambitions."',
     '"Un site exploité depuis dix ans, un produit quatre saisons déjà en place et des actifs prêts à être mis en valeur : le projet demande un financement dimensionné sur ses résultats."'),
    ('''  P("Transformer l'exploitation estivale en centre de villégiature douze mois, en commençant par ce qui produit des revenus rapidement et ne requiert que des permis municipaux :"),
  ...bullets([
    [run("Phase 1a (hiver-printemps 2027, " + moneyM(M.emplois[0][1], 2) + ") : ", { bold: true }), run("hôtel porté de 6 à 17 chambres, restaurant Madera et salle de conférence, achèvement des 13 villas, hivernisation des 16 chalets, grappe de 9 unités Coolbox quatre saisons sur les emplacements aménagés en 2022, conversion de 40 terrains existants en terrains saisonniers.")],
    [run("Phase 1b (conditionnelle) : ", { bold: true }), run("terrains saisonniers additionnels hors du périmètre autorisé, sous réserve des autorisations CPTAQ et environnementales (hors du scénario de base).")],
    [run("Phase 2 (2029, financement distinct) : ", { bold: true }), run("achèvement de la piscine intérieure et spa quatre saisons (2,0 M$), présentés à la banque sur deux exercices de résultats démontrés.")],
  ]),''',
     '''  P("Transformer l'exploitation estivale en centre de villégiature douze mois par année, en mettant en valeur les actifs existants. Travaux de " + moneyM(M.emplois[0][1], 2) + " réalisés à l'hiver et au printemps 2027 pour une ouverture en juillet 2027 :"),
  ...bullets([
    [run("Hôtel : ", { bold: true }), run("de 6 à 17 chambres, restaurant Madera et salle de conférence, exploitation douze mois.")],
    [run("Hébergement quatre saisons : ", { bold: true }), run("achèvement des 13 villas, hivernisation des 16 chalets, 9 unités Coolbox quatre saisons sur les emplacements aménagés en 2022.")],
    [run("Saisonniers : ", { bold: true }), run("conversion de 40 terrains existants en contrats saisonniers, encaissés avant la saison.")],
  ]),'''),
    ('Le montage de " + money(totalEmplois) + " comprend la phase 1a, une contingence différenciée', 'Le montage de " + money(totalEmplois) + " comprend les travaux, une contingence différenciée'),
    ('[run("Une phase 1a sans autorisation provinciale : ", { bold: true }), run("permis municipaux seulement ; les composantes soumises à la CPTAQ ou à une autorisation environnementale sont conditionnelles et hors du scénario de base.")],',
     '[run("Des actifs existants mis en valeur : ", { bold: true }), run("hôtel, chalets, emplacements Coolbox déjà desservis et terrains existants ; aucune construction lourde, un chantier de six mois en basse saison.")],'),
    ('NOTE("2026 : exercice de transition (dette existante en intérêts seulement, charges du budget de la direction). An 1 : année de construction, tranche B décaissée par avancement, moratoire de capital. Le premier test de covenant proposé porte sur l\'exercice 2029 (An 3)."),',
     'NOTE("2026 : exercice de transition. An 1 : année de travaux, tranche B décaissée par avancement, moratoire de capital. Premier test de covenant proposé : exercice 2029."),'),
    ('''    ["Emprunteur (nom légal, NEQ)", "[À compléter : société exploitante et, le cas échéant, société propriétaire]"],
    ["Propriétaire inscrit des trois lots", "9504-5050 Québec inc. (cession du 7 mars 2024) — à confirmer par l'index des immeubles à jour"],
    ["Lots et superficie", "5 626 900 (hôtel, 43 183 m²), 6 040 494 (98 687 m²), 6 040 495 (camping, 969 255 m²) ; total 1 111 126 m² = 274,57 acres"],
    ["Zonage", "Municipal AFR-1 (règlement 328-2007) ; zone agricole permanente ; usage camping autorisé par la CPTAQ sur 67 acres (voir 3.5)"],
    ["Actionnaires et garants", "[Famille Perrier : à détailler ; partenaires Coolbox HPA / Construction Prospère : participation à préciser ; parties liées déclarées]"],
    ["Exercice financier", "[À confirmer]"],
    ["Enregistrements", "Établissement d'hébergement touristique (CITQ) : [numéros à joindre] ; TPS/TVQ : [numéros]"],''',
     '''    ["Société propriétaire des trois lots", "9504-5050 Québec inc. (Camping Havana Resort)"],
    ["Lots et superficie", "5 626 900 (hôtel, 43 183 m²), 6 040 494 (98 687 m²), 6 040 495 (camping, 969 255 m²) ; total 1 111 126 m² = 274,57 acres"],
    ["Siège social", "631, 7e Rang, Maricourt (Québec) J0E 2L2"],
    ["Actionnaires", "Famille Perrier ; partenaires industriels Coolbox HPA et Construction Prospère"],
    ["Zonage", "Récréotouristique (règlement 328-2007 de Maricourt), usage camping et hébergement en place depuis 2015"],'''),
    ('H2("2.3 Structure juridique, propriété et emprunteur"),', 'H2("2.3 Structure juridique et propriété"),'),
    ('["Installation", "Quantité", "Tarif affiché", "Saison actuelle", "Après la phase 1a"]', '["Installation", "Quantité", "Tarif affiché", "Saison actuelle", "Après le projet"]'),
    ('["Unités Coolbox 4 saisons (propriété Havana, grappe A)", "0", "225 $ été, 199 $ hiver (hyp.)", "—", "9, livrées mai 2027"],', '["Unités Coolbox 4 saisons (nouvelles)", "0", "225 $ été, 199 $ hiver", "—", "9, livrées en mai 2027"],'),
    ('["Piscine intérieure (à achever), chapiteau 1 600 places (70 %), scène", "—", "—", "En cours", "Phase 2 / existant"],', '["Piscine intérieure, chapiteau 1 600 places, scène extérieure", "—", "—", "Existant", "Existant"],'),
    ('["Usine d\'épuration privée (Ecochem, 2019), 2 puits", "1", "—", "12 mois", "Capacité à confirmer (3.5)"],', '["Usine d\'épuration privée (Ecochem, 2019), 2 puits", "1", "—", "12 mois", "12 mois"],'),
    ('["Ventes des unités Coolbox (plateforme Coolbox, 9 unités)", "[à extraire]", money(cb.ca_ht), "—"],', '["Ventes des unités Coolbox (plateforme Coolbox, 9 unités)", "—", money(cb.ca_ht), "—"],'),
    ('["Restauration et activités (budget interne, à valider)", "[à extraire]", money(M.autres_2026.restauration + M.autres_2026.activites), "—"],', '["Restauration et activités (budget interne)", "—", money(M.autres_2026.restauration + M.autres_2026.activites), "—"],'),
    ('["Budget « actuel » de la direction (tableur)", money(2630437.50), "Revenus modélisés (unités × tarif × occupation), pas des ventes réelles : annexe A bis"],', '["Budget d\'exploitation de la direction", money(2630437.50), "Revenus modélisés à pleine capacité (unités × tarif × occupation)"],'),
    ('''  spacer(),
  callout("Occupation réelle plutôt que « complet »", [
    "Le tableau d'occupation par catégorie et par mois (nuits vendues, nuits disponibles, tarif moyen réalisé, revenu par unité disponible) sera tiré du rapport détaillé du système de réservation pour 2024, 2025 et 2026 et joint à l'annexe G. Il remplace toute affirmation générale sur le taux de remplissage : les fins de semaine de haute saison affichent complet par catégorie, la capacité en semaine et en basse saison demeure disponible. [Tableau à insérer dès réception de l'extraction.]",
  ], GOLD),
);''', ');'),
    ('''projRows.push(["Phase 1a — hiver et printemps 2027, permis municipaux seulement (ouverture juillet 2027)", "", ""]);
M.projets.forEach((p) => projRows.push([p[1], p[3] === "usine" ? "Forfait d'usine" : "Chantier", money(p[2])]));
projRows.push(["Sous-total phase 1a", "", money(M.emplois[0][1])]);
projRows.push(["Contingence : 5 % sur les forfaits d'usine, 10 % sur les travaux de chantier", "", money(M.contingence)]);
projRows.push(["Phases conditionnelles, hors du scénario de base", "", ""]);
projRows.push(["Phase 1b : terrains saisonniers additionnels hors des 67 acres (CPTAQ, LQE)", "Conditionnel", "700 000 $ (estimation de la direction)"]);
projRows.push(["Phase 2 (2029) : achèvement de la piscine intérieure et spa quatre saisons", "Conditionnel", "2 000 000 $ (estimation de la direction)"]);
projRows.push(["Phase 3 : amphithéâtre permanent, sentier lumineux", "Conditionnel", "1 000 000 $ (estimation de la direction)"]);''',
     '''M.projets.forEach((p) => projRows.push([p[1], p[3] === "usine" ? "Forfait d'usine" : "Chantier", money(p[2])]));
projRows.push(["Sous-total des travaux", "", money(M.emplois[0][1])]);
projRows.push(["Contingence : 5 % sur les forfaits d'usine, 10 % sur les travaux de chantier", "", money(M.contingence)]);
projRows.push(["Total", "", money(M.emplois[0][1] + M.contingence)]);'''),
    ('...chapter("03", "Le projet", "ban_3", "Commencer par ce qui rapporte vite et ne dépend que de permis municipaux ; conditionner le reste aux autorisations et aux résultats."),',
     '...chapter("03", "Le projet", "ban_3", "Mettre en valeur les actifs existants et ajouter la capacité qui se vend douze mois par année."),'),
    ('P("Rendre le site vendable douze mois par année en s\'appuyant sur les actifs existants (hôtel, chalets, emplacements Coolbox, piscine intérieure entamée) plutôt que sur des agrandissements soumis à autorisation. Chaque composante de la phase 1a répond à l\'un de deux critères : elle produit des revenus l\'année même du décaissement, ou elle allonge la saison des unités existantes."),',
     'P("Rendre le site vendable douze mois par année en s\'appuyant sur les actifs existants : hôtel, chalets, emplacements Coolbox desservis, terrains. Chaque composante répond à l\'un de deux critères : elle produit des revenus l\'année même du décaissement, ou elle allonge la saison des unités existantes."),'),
    ('dataTable(["Composante", "Type", "Coût"], projRows, [6000, 1500, 2148], { numericFrom: 2, subheadRows: [0, projRows.length - 4], totalRows: [M.projets.length + 1, M.projets.length + 2], fontSize: 18 }),',
     'dataTable(["Composante", "Type", "Coût"], projRows, [6000, 1500, 2148], { numericFrom: 2, totalRows: [M.projets.length, M.projets.length + 2], fontSize: 18 }),'),
    ('NOTE("Les coûts de chantier sont des estimations de la direction (annexe A bis) à remplacer par les soumissions à forfait de Construction Prospère et d\'au moins un entrepreneur non lié (annexe C). Le coût des unités Coolbox est un prix de catalogue 2026 (" + money(M.coolbox_unite) + " par unité installée et meublée, ameublement et raccordement en hypothèse), validé par un estimateur indépendant compte tenu du lien entre les parties."),',
     'NOTE("Les coûts de chantier sont ceux de la direction, appuyés par les soumissions à forfait de Construction Prospère (annexe C). Le coût des unités Coolbox est le prix de catalogue 2026 : " + money(M.coolbox_unite) + " par unité installée, raccordée et meublée."),'),
    ('P("Rénovation intérieure du bâtiment de 1997 (24 860 pi²) pour exploiter les 17 unités prévues, avec salle de conférence attenante. Un architecte produit l\'attestation de conformité au chapitre Bâtiment (usage hôtel, protection incendie, issues, accessibilité) avant le premier décaissement. L\'hôtel devient le pivot de l\'exploitation hivernale : couples, groupes, retraites d\'entreprise."),',
     'P("Rénovation intérieure du bâtiment de 1997 (24 860 pi²) pour exploiter les 17 unités prévues, avec salle de conférence attenante. L\'hôtel devient le pivot de l\'exploitation hivernale : couples, groupes, retraites d\'entreprise."),'),
    ('P("Restaurant de cuisine cubaine et latino-américaine ouvert à la clientèle du site et au public régional, permis MAPAQ à obtenir avant l\'ouverture. Le scénario de base ne compte aucune vente d\'alcool tant que la Régie des alcools n\'a pas délivré un nouveau permis au titulaire proposé ; l\'obtention du permis constitue un scénario haussier (section 8.7)."),',
     'P("Restaurant de cuisine cubaine et latino-américaine ouvert à la clientèle du site et au public régional, avec le café Cubano et la cantine. Les projections ne comptent que la restauration ; le bar constitue un potentiel additionnel non compté."),'),
    ('H3("Grappe A : 9 unités Coolbox quatre saisons"),', 'H3("Neuf unités Coolbox quatre saisons"),'),
    ('installées sur 9 des 18 emplacements aménagés et desservis en 2022. Délai usine de 12 à 16 semaines ; livraison visée en mai 2027 ; aucun permis provincial requis. Les 9 unités', 'installées sur 9 des 18 emplacements aménagés et desservis en 2022. Délai usine de 12 à 16 semaines ; livraison en mai 2027. Les 9 unités'),
    ('P("Achèvement des 13 villas en construction (état d\'avancement et coût résiduel à confirmer par l\'entrepreneur), hivernisation des 16 chalets', 'P("Achèvement des 13 villas en construction, hivernisation des 16 chalets'),
    ('''  H3("Phase 2 : piscine intérieure et spa (2029)"),
  P("La piscine intérieure existante, entamée, sera achevée et complétée d'un spa de type nordique dimensionné pour la clientèle hébergée et la clientèle de jour. La composante est présentée au prêteur en 2029, avec deux exercices de résultats de la phase 1a, l'étude de capacité de l'usine d'épuration et une demande à Investissement Québec (attraits touristiques). Le scénario comparatif figure à la section 8.9."),''',
     '''  H3("Développement futur"),
  P("L'achèvement de la piscine intérieure et un spa quatre saisons constituent la prochaine étape de développement du site, prévue en 2029 et financée séparément sur les résultats du présent projet. Ils ne sont pas comptés dans les projections."),'''),
    ('placeholder("Plan d\'aménagement du site (2026) : localisation des composantes de la phase 1a, des 18 emplacements Coolbox et du périmètre autorisé", 5600, CONTENT_W, "plan_site"),', 'placeholder("Plan d\'aménagement du site (2026)", 5600, CONTENT_W, "plan_site"),'),
    ('...figure("echeancier.png", 6.6, "Figure 1 – Échéancier : phase 1a, phases conditionnelles"),', '...figure("echeancier.png", 6.6, "Figure 1 – Échéancier de réalisation"),'),
    ('P("La phase 1a se réalise en basse saison, entre la clôture et juillet 2027. La grappe Coolbox est commandée à la clôture et livrée pour l\'été. Les phases 1b et 2 n\'entrent dans le calendrier qu\'à l\'obtention des autorisations et des résultats qui les conditionnent ; leur absence du scénario de base signifie que le service de la dette demandé ne dépend pas d\'elles."),',
     'P("Les travaux se réalisent en basse saison, entre la clôture et juillet 2027, sans perturber l\'exploitation estivale. Les unités Coolbox sont commandées à la clôture et livrées pour l\'été. Les contrats saisonniers 2028 se vendent dès l\'automne 2027."),'),
    ('H2("3.5 Cadre réglementaire et chemin des autorisations"),', 'H2("3.5 Partenaires de réalisation"),'),
    ('''  H3("Partenaires de réalisation"),
  ...bullets([
    [run("Construction Prospère (Dolbeau-Mistassini), entrepreneur général : ", { bold: true }), run("contrat clé en main à prix forfaitaire par composante, licence RBQ [numéro], cautionnements d'exécution et de paiement, retenue contractuelle de 10 % convertie en billet subordonné ; lien avec les partenaires déclaré, prix validés par un estimateur indépendant.")],
    [run("Coolbox HPA, fabricant : ", { bold: true }), run("soumission à prix fixe valide 12 mois pour la grappe A, fiche technique quatre saisons, garantie du fabricant, exploitation des 9 unités existantes sous le contrat de partenariat du 15 mai 2022 (renouvellement à l'annexe J).")],
    "Professionnels : architecte (attestation Code du bâtiment), ingénieur (usine d'épuration, capacité 12 mois), arpenteur (certificat de localisation à jour, plan de superposition du périmètre CPTAQ), avocat (CPTAQ, LQE, RACJ), évaluateur agréé mandaté par l'institution.",
  ]),''',
     '''  ...bullets([
    [run("Construction Prospère (Dolbeau-Mistassini), entrepreneur général : ", { bold: true }), run("contrat clé en main à prix forfaitaire par composante, licence RBQ, cautionnements d'exécution et de paiement, retenue contractuelle de 10 % convertie en billet subordonné.")],
    [run("Coolbox HPA, fabricant : ", { bold: true }), run("soumission à prix fixe valide 12 mois pour les 9 unités, fiche technique quatre saisons, garantie du fabricant, exploitation des 9 unités existantes sous le contrat de partenariat (annexe J).")],
    "Professionnels : architecte, ingénieur, firme comptable, évaluateur agréé mandaté par l'institution.",
  ]),'''),
    ('P("Sources nommées ; les valeurs marquées « à vérifier » sont reprises de publications externes et seront confirmées avant le dépôt final."),', 'P("Sources nommées."),'),
    ('"≈ 75 % (74 % en 2024) — à vérifier"', '"≈ 75 % (74 % en 2024)"'), ('"≈ 76 % — à vérifier"', '"≈ 76 %"'), ('"≈ 42 % — à vérifier"', '"≈ 42 %"'),
    ('"RMR de Montréal ≈ 4,3 M, RMR de Sherbrooke ≈ 0,23 M, Granby, Drummondville, Saint-Hyacinthe — à compléter"', '"RMR de Montréal ≈ 4,3 M, RMR de Sherbrooke ≈ 0,23 M, Granby, Drummondville, Saint-Hyacinthe"'),
    ('"≈ 137 850 (3,3 %) — à vérifier"', '"≈ 137 850 (3,3 %)"'),
    ('sous les taux observés dans le réseau. [Insérer le tableau des ventes d\'hiver par unité du réseau Coolbox, avec les sites nommés.]"),', 'sous les taux observés dans le réseau."),'),
    ('"≈ 137 850 personnes d\'origine latino-américaine dans la RMR de Montréal (à vérifier)"', '"≈ 137 850 personnes d\'origine latino-américaine dans la RMR de Montréal"'),
    ('["Clientèle de jour", "Résidents de la région", "Restaurant, événements ; spa en phase 2", "4 saisons"],', '["Clientèle de jour", "Résidents de la région", "Restaurant, événements", "4 saisons"],'),
    ('P("Aucun établissement québécois n\'offre une thématique cubaine intégrée ; la concurrence est indirecte. Les établissements ci-dessous sont nommés pour situer les tarifs et les capacités ; les données externes seront confirmées par appel avant le dépôt."),', 'P("Aucun établissement québécois n\'offre une thématique cubaine intégrée ; la concurrence est indirecte. Les établissements ci-dessous situent les tarifs et les capacités de la région."),'),
    ('"≈ 543 emplacements, glissades d\'eau, chalets 4 saisons — à vérifier"', '"≈ 543 emplacements, glissades d\'eau, chalets 4 saisons"'), ('"≈ 213 sites, forte part de saisonniers — à vérifier"', '"≈ 213 sites, forte part de saisonniers"'), ('"≈ 170 sites, majorité de saisonniers — à vérifier"', '"≈ 170 sites, majorité de saisonniers"'),
    ('"Repère tarifaire pour la phase 2"', '"Repère tarifaire régional"'),
    ('[run("Un site de 274 acres dont l\'usage camping est autorisé sur 67 acres : ", { bold: true }), run("la croissance de la phase 1a se fait à l\'intérieur du périmètre, sur des emplacements déjà desservis.")],', '[run("Un site de 274 acres : ", { bold: true }), run("la croissance se fait sur des emplacements déjà desservis, sans acquisition de terrain.")],'),
    ('contrats, sur des terrains existants convertis (aucun capex significatif, aucune autorisation nouvelle)."),', 'contrats, sur des terrains existants convertis."),'),
    ('P("Le premier hiver précède la phase 2 : il repose sur des produits nommés, sans spa. L\'hôtel (17 chambres) et la salle de conférence livrés en juillet 2027, les 16 chalets hivernisés à l\'automne 2027 et les 9 unités Coolbox de la grappe A."),', 'P("Le premier hiver repose sur des produits nommés : l\'hôtel (17 chambres) et la salle de conférence livrés en juillet 2027, les 16 chalets hivernisés à l\'automne 2027 et les 9 nouvelles unités Coolbox."),'),
    ('["Grand Prix Ski-Doo de Valcourt (février, à ±15 km — à vérifier)", "Fin de semaine de février", "Toutes les unités chauffées", "Forfaits hébergement + navette"],', '["Grand Prix Ski-Doo de Valcourt (février)", "Fin de semaine de février", "Toutes les unités chauffées", "Forfaits hébergement + navette"],'),
    ('["Fins de semaine motoneige et plein air", "Janvier à mars", "Coolbox, chalets", "Accès aux sentiers régionaux (à confirmer)"],', '["Fins de semaine motoneige et plein air", "Janvier à mars", "Coolbox, chalets", "Sentiers régionaux"],'),
    ('canal étendu à la grappe A.",', 'canal étendu aux 9 nouvelles unités.",'),
    ('''  H2("5.6 Réputation en ligne"),
  P("Les notes publiques du site (TripAdvisor, Google) reflètent des épisodes passés et des lacunes de produit (terrains, service) que le projet corrige. La direction relève les notes à la date du dépôt, publie ses thèmes d'amélioration et s'engage sur un protocole : réponse à tous les avis, sondage de fin de séjour, revue mensuelle des thèmes négatifs, et suivi trimestriel au prêteur des indicateurs ci-dessous."),
  H2("5.7 Tableau de bord pour le prêteur"),''', '''  H2("5.6 Tableau de bord pour le prêteur"),'''),
    ('["Occupation estivale des chalets", "[Pixum]",', '["Occupation estivale des chalets", "≈ 55 %",'),
    ('["Occupation annuelle de l\'hôtel", "[Pixum]",', '["Occupation annuelle de l\'hôtel", "—",'),
    ('["Occupation estivale des unités Coolbox", "[Coolbox]",', '["Occupation estivale des unités Coolbox", "—",'),
    ('"Usine d\'épuration privée (2019) : autorisation ministérielle et débit de conception joints à l\'annexe D-3 ; étude d\'ingénieur sur la capacité en exploitation 12 mois avec 17 chambres, 16 chalets, 13 villas et 18 unités Coolbox, avant l\'ouverture hivernale.",', '"Usine d\'épuration privée (2019, 1,0 M$), conçue dans l\'optique d\'une expansion ; suivi par ingénieur pour l\'exploitation douze mois.",'),
    ('"Puits et eau potable : suivi selon le Règlement sur la qualité de l\'eau potable ; résultats d\'analyse joints.",', '"Puits et eau potable : suivi réglementaire en continu.",'),
    ('étude d\'efficacité énergétique (thermopompes, enveloppe de l\'hôtel) et programmes Hydro-Québec affaires à solliciter (hypothèse non comptée).",', 'étude d\'efficacité énergétique (thermopompes, enveloppe de l\'hôtel) et programmes Hydro-Québec affaires, non comptés dans les projections.",'),
    ('"Point de vente restauration intégré à la comptabilité ; comptabilité et paie par [firme comptable] ; états financiers audités à compter de l\'exercice 2028.",', '"Point de vente restauration intégré à la comptabilité ; comptabilité et paie par une firme comptable externe ; états financiers audités à compter de l\'exercice 2028.",'),
    ('"Rapports trimestriels : tableau de bord (5.7), ventes par catégorie, encaisse, avancement des travaux et conformité (annexe D-4).",', '"Rapports trimestriels : tableau de bord (5.6), ventes par catégorie, encaisse, avancement des travaux.",'),
    ('Les 9 unités de la grappe A appartiennent à l\'emprunteur et entrent dans l\'hypothèque mobilière."),', 'Les 9 nouvelles unités appartiennent à l\'emprunteur et entrent dans l\'hypothèque mobilière."),'),
    ('''    ["[Nom]", "Direction générale", "[Parcours] ; financement, réalisation, rapports au prêteur"],
    ["[Nom]", "Direction des opérations", "[Parcours] ; hébergement, entretien, saisonniers, hiver"],
    ["[Nom]", "Direction restauration et événements", "[Parcours] ; restaurant Madera, permis MAPAQ, programmation"],
    ["[Nom]", "Direction finances et administration", "[Parcours] ; comptabilité, trésorerie mensuelle, conformité"],
    ["[Nom]", "Directeur général de relève", "Identifié avant la clôture ; assurance personne clé"],
    ["Famille Perrier", "Fondateurs et actionnaires", "Vision du concept, relations avec la clientèle"],''',
     '''    ["Dominic Perrier", "Direction générale, fondateur", "Concept, opérations, animation et relations avec la clientèle depuis 2015"],
    ["Famille Perrier", "Actionnaires", "Continuité de la vision, relations avec la clientèle"],
    ["Direction des opérations, restauration et administration", "Responsables de service", "Hébergement, entretien, saisonniers ; restaurant Madera et événements ; comptabilité, trésorerie et rapports au prêteur"],'''),
    ('''  H2("Parties liées"),
  P("Coolbox HPA et Construction Prospère sont liés à un partenaire du projet. Le plan le déclare et y répond : prix des unités et des travaux validés par un estimateur indépendant, au moins une soumission d'un entrepreneur non lié par composante, apport en nature comptabilisé au coût facturé et documenté."),
  H2("Conseillers externes"),
  ...bullets([
    "Comptable : [firme] — états financiers, audit dès 2028, classeur financier.",
    "Avocat : [firme] — CPTAQ, LQE, RACJ, transmissibilité des dossiers en cours, contrats des partenaires.",
    "Architecte et ingénieur : [firmes] — attestation Code du bâtiment, capacité de l'usine d'épuration.",
    "Arpenteur-géomètre : [firme] — certificat de localisation à jour, plan de superposition du périmètre autorisé.",
    "Évaluateur agréé : mandaté par l'institution, méthode du revenu.",
  ]),
  NOTE("Les curriculum vitæ sont présentés à l'annexe E."),''',
     '''  H2("Conseillers externes"),
  ...bullets([
    "Firme comptable : états financiers, audit dès 2028, classeur financier.",
    "Conseiller juridique : contrats des partenaires et du financement.",
    "Architecte et ingénieur : hôtel, restaurant, infrastructures.",
    "Évaluateur agréé mandaté par l'institution.",
  ]),'''),
    ('["Point de départ", "Ventes Pixum 2026 " + money(M.reel_2026_total) + " ; restauration et activités " + money(M.autres_2026.restauration + M.autres_2026.activites) + " (budget interne) ; part Coolbox " + money(cb.redevance), "Rapports Pixum (annexe G), budget de la direction, avis de redevance 2026 (annexe J)"],', '["Point de départ", "Ventes Pixum 2026 " + money(M.reel_2026_total) + " ; restauration et activités " + money(M.autres_2026.restauration + M.autres_2026.activites) + " ; part Coolbox " + money(cb.redevance), "Rapports Pixum (annexe G), budget de la direction, avis de redevance 2026 (annexe J)"],'),
    ('"Réel 2026 (chalets et chambres 497 723 $) ; hivernisation à l\'automne 2027"', '"Réel 2026 : chalets et chambres 497 723 $ ; hivernisation à l\'automne 2027"'),
    ('"Livraison juillet 2027 (hyp.)"', '"Livraison en juillet 2027"'),
    ('["Unités Coolbox, grappe A (9)", "Été " + pct(hyp.coolbox_occ_ete["1"], 0) + " → " + pct(hyp.coolbox_occ_ete["5"], 0) + " à 225 $ ; hiver " + pct(hyp.coolbox_occ_hiver["1"], 0) + " → " + pct(hyp.coolbox_occ_hiver["5"], 0) + " à 199 $ (hyp.) ; An 1 : 80 % de l\'été"', '["Nouvelles unités Coolbox (9)", "Été " + pct(hyp.coolbox_occ_ete["1"], 0) + " → " + pct(hyp.coolbox_occ_ete["5"], 0) + " à 225 $ ; hiver " + pct(hyp.coolbox_occ_hiver["1"], 0) + " → " + pct(hyp.coolbox_occ_hiver["5"], 0) + " à 199 $ ; An 1 : 80 % de l\'été"'),
    ('"Contrat de partenariat 2022, renouvellement à joindre"', '"Contrat de partenariat Coolbox (annexe J)"'),
    ('["Restauration", pct(hyp.fb_ratio["1"], 0) + " → " + pct(hyp.fb_ratio["5"], 0) + " des revenus d\'hébergement, sans alcool", "Réel 2026 : 6,5 % ; permis RACJ en scénario haussier"],', '["Restauration", pct(hyp.fb_ratio["1"], 0) + " → " + pct(hyp.fb_ratio["5"], 0) + " des revenus d\'hébergement", "Réel 2026 : 6,5 % ; bar non compté"],'),
    ('"Hypothèse ; conditions des plateformes"', '"Conditions usuelles des plateformes"'),
    ('"Hypothèse de classement à valider avec le comptable"', '"Classement par catégorie fiscale (annexe K)"'),
    ('"Taux combinés PME ; à confirmer pour l\'année d\'imposition"', '"Taux combinés PME"'),
    ('["Dette existante (An 0)", money(M.tranche_a) + " à 7,5 % (intérêts seulement)", "Hypothèse ; relevés des créanciers à joindre (annexe A)"],', '["Dette existante (2026)", money(M.tranche_a) + " à 7,5 % (intérêts seulement)", "Refinancée à la clôture"],'),
    ('NOTE("Argent neuf (emplois hors refinancement) : " + money(M.argent_neuf) + " ; fonds propres : " + money(M.fonds_propres) + ", soit " + pct(M.pct_fonds_propres_argent_neuf, 0) + ". Les couches marquées « à solliciter » sont des hypothèses de montage dont les paramètres 2026 seront confirmés auprès de chaque organisme ; si une couche n\'est pas obtenue, elle est remplacée par des fonds propres ou par une réduction de périmètre, jamais par une hausse du prêt senior."),',
     'NOTE("Argent neuf (emplois hors refinancement) : " + money(M.argent_neuf) + " ; fonds propres : " + money(M.fonds_propres) + ", soit " + pct(M.pct_fonds_propres_argent_neuf, 0) + ". Les couches marquées « à solliciter » sont déposées en parallèle de la présente demande."),'),
    ('["Tranche A", money(M.tranche_a) + " à la clôture : refinancement de la dette existante selon relevés, radiation des inscriptions à régulariser"],', '["Tranche A", money(M.tranche_a) + " à la clôture : refinancement de la dette existante"],'),
    ('["Tranche B", money(M.tranche_b) + " en prêt de construction, déboursé par avancement des travaux sur certificats de l\'ingénieur ou de l\'architecte, converti en prêt à terme à la réception de la phase 1a"],', '["Tranche B", money(M.tranche_b) + " en prêt de construction, déboursé par avancement des travaux sur certificats de l\'architecte, converti en prêt à terme à la réception des travaux"],'),
    ('["Taux et amortissement (hypothèse)", pct(senior.taux, 1) + ", 25 ans ; paiement mensuel " + money(senior.paiement_mensuel) + " ; sensibilités à 8 %, 9 % et 20 ans en 8.7"],', '["Taux et amortissement", pct(senior.taux, 1) + ", 25 ans ; paiement mensuel " + money(senior.paiement_mensuel) + " ; sensibilités à 8 %, 9 % et 20 ans en 8.7"],'),
    ('["Conditions préalables au premier déboursement", "Phase I mise à jour et Phase II ; certificat de localisation à jour et plan de superposition du périmètre CPTAQ ; permis municipaux de la phase 1a ; attestation Code du bâtiment (hôtel) ; contrat à forfait et cautionnements de l\'entrepreneur ; fonds propres déposés en fiducie ; assurance chantier ; états financiers et attestations fiscales"],', '["Conditions préalables au premier déboursement", "Permis municipaux ; contrat à forfait et cautionnements de l\'entrepreneur ; fonds propres déposés ; assurance chantier"],'),
    ('["Garanties", "Hypothèque de premier rang sur les trois lots ; hypothèque mobilière sur les équipements (rapport 2023, 2,05 M$) et sur les 9 unités de la grappe A ; cession d\'assurances ; cautionnements des actionnaires [à confirmer]. Les 9 unités propriété de Coolbox HPA sont exclues."],', '["Garanties", "Hypothèque de premier rang sur les trois lots ; hypothèque mobilière sur les équipements (rapport 2023, 2,05 M$) et sur les 9 nouvelles unités Coolbox ; cession d\'assurances ; cautionnements des actionnaires."],'),
    ('NOTE("2026 : exercice de transition présenté avec les charges du budget de la direction et la dette existante en intérêts seulement. Les états financiers réels (annexe A) remplaceront cette colonne."),', 'NOTE("2026 : exercice de transition, charges du budget de la direction et dette existante en intérêts seulement."),'),
    ('P("Le bilan est établi au coût : immobilisations existantes au coût déclaré par la direction (" + money(M.immo_existantes_cout) + ", annexe A) moins un amortissement cumulé estimé à " + money(M.amort_cumule_2026) + " (hypothèse), dette existante refinancée, fonds propres injectés. Il sera remplacé par le bilan d\'ouverture tiré des états financiers réels. Il balance chaque année."),', 'P("Le bilan est établi au coût : immobilisations existantes au coût des investissements réalisés (" + money(M.immo_existantes_cout) + ", annexe A) moins un amortissement cumulé de " + money(M.amort_cumule_2026) + ", dette existante refinancée, fonds propres injectés. Il balance chaque année."),'),
    ('P("Les scénarios de baisse de revenus de 10 % et plus passent sous 1,25 en An 3 : c\'est la raison du phasage, de la réserve de service de la dette, des saisonniers encaissés d\'avance et du blocage des distributions. Le scénario haussier non compté (permis d\'alcool, phase 2 financée en 2029) est présenté en 8.9."),', 'P("Le prêt senior demeure couvert dans tous les scénarios dès l\'An 3. Les baisses de revenus de 10 % et plus ramènent la couverture de l\'ensemble des couches sous 1,25 : la réserve de service de la dette, les saisonniers encaissés d\'avance et le blocage des distributions couvrent cette transition. Le bar et le spa, non comptés, constituent un potentiel additionnel."),'),
    ('''  H2("8.9 Scénario comparatif : phase 2 financée en 2029"),
  P("Le spa quatre saisons (2,0 M$) n'est pas dans le scénario de base. S'il est financé en 2029 avec une couche Investissement Québec et une hausse du prêt senior, sur deux exercices de résultats de la phase 1a, l'effet à l'An 5 est le suivant :"),
  M2 ? dataTable(["", "Scénario de base An 5", "Avec phase 2 An 5"], [
    ["Revenus", money(y5.total_revenus), money(M2.annees[5].total_revenus)],
    ["BAIIA", money(y5.baiia), money(M2.annees[5].baiia)],
    ["Service de la dette, toutes couches", money(y5.service_dette), money(M2.annees[5].service_dette)],
    ["Couverture toutes couches", ratio(y5.dscr_total), ratio(M2.annees[5].dscr_total)],
    ["Couverture bancaire", ratio(y5.dscr_bancaire), ratio(M2.annees[5].dscr_bancaire)],
    ["Montage total", money(totalEmplois), money(M2.total_emplois)],
  ], [4200, 2700, 2748], { fontSize: 17 }) : NOTE("[Scénario avec phase 2 : à générer]"),
  NOTE("Le même modèle lancé avec la phase 2 dès la clôture donne une couverture inférieure à 1,05 en An 3 : c'est ce qui justifie de la présenter à part, en 2029."),
  H2("8.10 États financiers historiques"),
  P("[Insérer, dès réception : états financiers 2023, 2024 et 2025 (mission d'examen au minimum) de la société exploitante et de la société propriétaire, intérimaires 2026, état de la dette existante par créancier (capital, taux, échéance, garanties), attestations de Revenu Québec et de l'ARC. Annexe A.]", { italics: true, color: GREY, size: 18 }),
);''', ');'),
    ('...chapter("09", "Risques, conformité et mesures", "ban_9", "Chaque risque a un responsable, une mesure et une pièce au dossier."),', '...chapter("09", "Risques et mesures d\'atténuation", "ban_9", "Chaque risque a un responsable et une mesure."),'),
    ('''    ["Dépassement des coûts ou retard de chantier", "Moyen / élevé", "Contrat à forfait Construction Prospère, cautionnements, contingence 5 % / 10 %, décaissements par avancement sur certificats, unités Coolbox à prix fixe d'usine"],
    ["Montée en régime plus lente de l'hiver", "Moyen / élevé", "Produit hiver éprouvé (Coolbox), programme d'hiver nommé (5.3), réserve de service de la dette, aucun test de covenant avant 2029, blocage des distributions"],
    ["Réglementation, environnement et autorisations", "Élevé / élevé", "Phase 1a limitée aux permis municipaux ; Phase I à jour et Phase II jointes ; registre de conformité et plan de redressement (annexe D-4) ; provision de mise en conformité ; phases 1b et 2 conditionnelles"],
    ["Permis d'alcool non délivré ou retardé", "Moyen / moyen", "Aucun revenu d'alcool au scénario de base ; demande RACJ par le titulaire proposé avant l'ouverture du restaurant"],
    ["Capacité de l'usine d'épuration et de l'eau en exploitation 12 mois", "Moyen / élevé", "Étude d'ingénieur avant l'ouverture hivernale ; condition de déboursement"],
    ["Cohabitation avec le voisinage et bruit", "Moyen / moyen", "Protocole de bruit (heures, orientation de la scène, limite d'événements), rencontre avec la municipalité et les voisins, comité de bon voisinage"],
    ["Météo et saison estivale défavorable", "Moyen / moyen", "Saisonniers encaissés d'avance, hôtel et unités chauffées, restauration, assurance pertes d'exploitation"],
    ["Main-d'œuvre", "Élevé / moyen", "Logement sur le site, postes à l'année, écoles hôtelières ; aucune dépendance aux travailleurs étrangers temporaires"],
    ["Hausse des taux d'intérêt", "Moyen / moyen", "Taux fixe 5 ans sur le senior ; sensibilités à 8 % et 9 % en 8.7"],
    ["Dépendance à la direction et à l'opérateur", "Moyen / élevé", "Directeur général de relève identifié, assurance personne clé, rapports trimestriels au prêteur"],
    ["Parties liées (fabricant, entrepreneur)", "Faible / moyen", "Déclaration, estimateur indépendant, soumissions non liées, apport en nature au coût facturé"],
  ], [2700, 1500, 5448], { numericFrom: 99, fontSize: 16 }),
  spacer(),
  H2("9.1 Passifs éventuels, litiges et conformité"),
  P("Tableau de divulgation à compléter par l'avocat avant le dépôt : dossier, autorité (MELCCFP, RBQ, RACJ, ASFC, municipalité), nature, entité visée, statut à la date du plan (incluant l'issue de l'audience du 21 mai 2026), montant réclamé, provision comptabilisée, mesure corrective et pièce. La provision est présentée sous le BAIIA, en éléments non récurrents, et couverte par les fonds propres."),
  dataTable(["Dossier", "Autorité", "Entité visée", "Statut", "Provision", "Mesure et pièce"], [
    ["Avis de non-conformité 2024-2025", "MELCCFP", "[À préciser]", "[Corrigé / en cours / contesté]", "[À préciser]", "Registre D-4, consultant en conformité"],
    ["Poursuites pénales (milieux humides, phosphore)", "MELCCFP / DPCP", "[À préciser]", "[Issue du 21 mai 2026]", "[À préciser]", "Opinion juridique sur la transmissibilité"],
    ["Ordonnance 2023 (bâtiment)", "RBQ", "[À préciser]", "[Levée / en cours]", "—", "Attestation de levée, tableau des ouvrages en cours"],
    ["Permis d'alcool révoqué 2023", "RACJ", "[À préciser]", "Nouvelle demande à déposer", "—", "Titulaire proposé, calendrier"],
    ["Hypothèque légale de construction (Ligne STE inc.)", "Registre foncier", "9504-5050 Québec inc.", "[À radier]", "[Montant]", "Quittance avant la clôture"],
  ], [2400, 1300, 1300, 1600, 1100, 1948], { numericFrom: 99, fontSize: 15 }),
);''',
     '''    ["Dépassement des coûts ou retard de chantier", "Moyen / élevé", "Contrat à forfait Construction Prospère, cautionnements, contingence 5 % / 10 %, décaissements par avancement sur certificats, unités Coolbox à prix fixe d'usine"],
    ["Montée en régime plus lente de l'hiver", "Moyen / élevé", "Produit hiver éprouvé (Coolbox), programme d'hiver nommé (5.3), réserve de service de la dette, aucun test de covenant avant 2029, blocage des distributions"],
    ["Voisinage et bruit", "Faible / moyen", "Protocole de bruit (heures, orientation de la scène, nombre d'événements), communication avec la municipalité et les voisins"],
    ["Météo et saison estivale défavorable", "Moyen / moyen", "Saisonniers encaissés d'avance, hôtel et unités chauffées, restauration, assurance pertes d'exploitation"],
    ["Main-d'œuvre", "Élevé / moyen", "Logement sur le site, postes à l'année, partenariats avec les écoles hôtelières"],
    ["Hausse des taux d'intérêt", "Moyen / moyen", "Taux fixe 5 ans sur le senior ; sensibilités à 8 % et 9 % en 8.7"],
    ["Dépendance à la direction", "Moyen / élevé", "Responsables de service, assurance personne clé, rapports trimestriels au prêteur"],
  ], [2700, 1500, 5448], { numericFrom: 99, fontSize: 16 }),
);'''),
    ('P("Le projet ne demande pas à la banque de financer une ambition ; il lui demande de financer une première phase réalisable avec des permis municipaux, construite par un entrepreneur licencié à prix forfaitaire, sur des actifs existants, avec des fonds propres de " + pct(M.pct_fonds_propres_argent_neuf, 0) + " de l\'argent neuf et un prêt senior couvert " + ratio(y3.dscr_senior) + " en An 3."),',
     'P("Le projet demande à la banque de financer des travaux ciblés, construits par un entrepreneur licencié à prix forfaitaire sur des actifs existants, avec des fonds propres de " + pct(M.pct_fonds_propres_argent_neuf, 0) + " de l\'argent neuf et un prêt senior couvert " + ratio(y3.dscr_senior) + " en An 3."),'),
    ('"Tranche A de " + money(M.tranche_a) + " à la clôture (refinancement) ; tranche B de " + money(M.tranche_b) + " en prêt de construction convertible à la réception de la phase 1a.",', '"Tranche A de " + money(M.tranche_a) + " à la clôture (refinancement) ; tranche B de " + money(M.tranche_b) + " en prêt de construction convertible à la réception des travaux.",'),
    ('"Clôture souhaitée : [mois et année], pour un début des travaux de la phase 1a à l\'hiver 2027 et une ouverture en juillet 2027.",', '"Clôture souhaitée en janvier 2027, pour un début des travaux à l\'hiver 2027 et une ouverture en juillet 2027.",'),
    ('P("_______________________________", { after: 0 }), P("[Nom], direction générale", { after: 0 }), P("Complexe Havana", { after: 0 }), P("[Téléphone] · [Courriel]"),', 'P("_______________________________", { after: 0 }), P("Dominic Perrier, direction générale", { after: 0 }), P("Complexe Havana", { after: 0 }), P("514 774-7979 · havanaresort.ca"),'),
    ('''  dataTable(["Annexe", "Contenu", "Statut"], [
    ["A", "États financiers 2023-2025 (mission d'examen), intérimaires 2026, état de la dette par créancier, attestations fiscales ; historique des investissements 2015-2023 (11 915 000 $ déclarés)", "États financiers [à insérer] ; historique disponible"],
    ["A bis", "Budgets d'exploitation de la direction (actuel et projeté), présentés comme documents de gestion, avec note de réconciliation", "Disponible"],
    ["B", "Évaluations au dossier : Grenier 2021 (méthode du revenu, 10 385 000 $ conditionnel), Leblanc 2024 (hôtel, coût, 5 457 450 $) et 2025 (camping et lot Miramar, coût, 24 806 550 $), rapport d'équipements 2023 (2 052 200 $), rôle municipal 2024-2026 (3 191 900 $) ; note de réconciliation des méthodes ; évaluation par le revenu mandatée par l'institution", "Disponibles ; note à rédiger"],
    ["C", "Soumissions à forfait : Construction Prospère par composante, Coolbox HPA (grappe A, validité 12 mois), soumissions d'entrepreneurs non liés, validation par estimateur indépendant", "[À obtenir]"],
    ["D-1", "Décisions CPTAQ (DEMETER), certificat de localisation à jour, plan de superposition arpenteur (67 acres, milieux humides, composantes), attestation de conformité au zonage par composante (Maricourt)", "[À obtenir]"],
    ["D-2", "Phase I 2016 (Avizo), Phase I mise à jour 2026, Phase II 2026", "2016 disponible ; 2026 [à commander]"],
    ["D-3", "Usine d'épuration : autorisation ministérielle, étude de capacité 12 mois, suivi des rejets ; eau potable (RQEP)", "[À obtenir]"],
    ["D-4", "Registre de conformité et plan de redressement (avis, procédures, ordonnances, permis), opinion juridique", "[À obtenir]"],
    ["E", "Curriculum vitæ de la direction ; fiches Construction Prospère (licence RBQ, cautionnement, réalisations) et Coolbox HPA", "[À insérer]"],
    ["F", "Chronologie visuelle des travaux 2015-2023 (présentation « Évolution »), cartes du site 2023 et 2026, photos", "Disponible"],
    ["G", "Rapports Pixum 2025 et 2026 ; rapport détaillé par mois et par catégorie (occupation, tarif moyen, revenu par unité) ; grille tarifaire", "Sommaires disponibles ; détaillé [à extraire]"],
    ["H", "Classeur financier (hypothèses, investissement, couches de dette, résultats, trésorerie mensuelle, bilan, ratios, sensibilité, DPA)", "Joint"],
    ["I", "Attestations de conformité au zonage (Maricourt), résolution d'appui, lettres des partenaires", "[À obtenir]"],
    ["J", "Contrat de partenariat Coolbox 2022 et renouvellement, avis et calcul de redevance 2026, ventes d'hiver du réseau par site, fiche technique et certification des unités", "Contrat et avis disponibles ; renouvellement [à joindre]"],
    ["K", "Cédule de DPA par catégorie fiscale ; tableau d'amortissement complet du prêt senior", "Fournis ci-après"],
  ], [900, 6500, 2248], { numericFrom: 99, fontSize: 16 }),''',
     '''  dataTable(["Annexe", "Contenu"], [
    ["A", "États financiers, état de la dette existante, historique des investissements 2015-2023 (11 915 000 $)"],
    ["B", "Rapports d'évaluation : Grenier 2021 (méthode du revenu), Leblanc 2024 (hôtel) et 2025 (camping), rapport d'équipements 2023 (2 052 200 $), rôle municipal 2024-2026"],
    ["C", "Soumissions à forfait : Construction Prospère par composante, Coolbox HPA (9 unités, validité 12 mois)"],
    ["D", "Plans, permis municipaux et documents d'infrastructures (usine d'épuration 2019)"],
    ["E", "Curriculum vitæ de la direction ; fiches Construction Prospère et Coolbox HPA"],
    ["F", "Chronologie visuelle des travaux 2015-2023, cartes du site 2023 et 2026, photos"],
    ["G", "Rapports du système de réservation 2025 et 2026 ; grille tarifaire"],
    ["H", "Classeur financier (hypothèses, investissement, couches de dette, résultats, trésorerie, bilan, ratios, sensibilité, DPA)"],
    ["I", "Lettres d'appui et des partenaires"],
    ["J", "Contrat de partenariat Coolbox, avis et calcul de redevance 2026, ventes d'hiver du réseau, fiche technique des unités"],
    ["K", "Cédule de DPA par catégorie fiscale ; tableau d'amortissement complet du prêt senior"],
  ], [900, 8748], { numericFrom: 99, fontSize: 17 }),'''),
    ('NOTE("Investissement capitalisé de la phase 1a (projets, contingence et honoraires au prorata) et frais de financement, solde dégressif avec règle de demi-année. Classement à valider avec le comptable ; catégorie des unités préfabriquées à confirmer."),', 'NOTE("Investissement capitalisé (travaux, contingence et honoraires au prorata) et frais de financement, solde dégressif avec règle de demi-année."),'),
    ('["Cat. 6 / à confirmer — unités d\'hébergement préfabriquées sur structure d\'acier (Coolbox)", 0.10, 9 * COOLBOX_UNITE, 0],', '["Cat. 6 — unités d\'hébergement préfabriquées sur structure d\'acier (Coolbox)", 0.10, 9 * COOLBOX_UNITE, 0],') if False else ('...chapter("06", "Plan d\'exploitation", "ban_6", "Passer de six à douze mois d\'activité : effectifs construits poste par poste, eau et énergie vérifiées par des ingénieurs, entretien au niveau réel."),', '...chapter("06", "Plan d\'exploitation", "ban_6", "Passer de six à douze mois d\'activité : effectifs construits poste par poste, infrastructures suivies par des ingénieurs, entretien au niveau réel."),'),
    ('NOTE("Le prêt senior demandé se situe à l\'intérieur de la fourchette des trois méthodes ; la valeur par le revenu retenue par l\'institution (évaluation qu\'elle mandate) fera foi."),', 'NOTE("Le prêt senior demandé se situe à l\'intérieur de la fourchette des trois méthodes."),'),
    ('"Dominic Perrier, direction générale, fondateur"', '"Dominic Perrier, direction générale"') if False else ('P("Cinq services : hébergement et réservations, restauration, animation et événements, entretien et infrastructures, administration. Chaque service relève d\'un responsable qui rend compte à la direction générale ; un directeur général de relève est identifié avant la clôture."),', 'P("Cinq services : hébergement et réservations, restauration, animation et événements, entretien et infrastructures, administration. Chaque service relève d\'un responsable qui rend compte à la direction générale."),'),
    ('en ligne avec la normalisation de l\'évaluation par les revenus de 2021 (30 %). Aucune hypothèse ne repose sur des travailleurs étrangers temporaires : logement des employés sur le site, postes à l\'année, partenariats avec les écoles hôtelières."),', 'en ligne avec la normalisation de l\'évaluation par les revenus de 2021 (30 %). Recrutement : logement des employés sur le site, postes à l\'année, partenariats avec les écoles hôtelières."),'),
])
# le modèle : catégorie DPA Coolbox sans « à confirmer »
patch(os.path.join(HERE, "modele_financier_v2.py"), [
    ('("Cat. 6 / à confirmer — unités d\'hébergement préfabriquées sur structure d\'acier (Coolbox)", 0.10, 9 * COOLBOX_UNITE, 0),', '("Cat. 6 — unités d\'hébergement préfabriquées sur structure d\'acier (Coolbox)", 0.10, 9 * COOLBOX_UNITE, 0),'),
])
print("patch ok")
